#!/bin/bash

# Get the path to the global gitignore file
GITIGNORE_FILE="${HOME}/.gitignore_global"

function search {
    result=`rg --ignore-case --ignore-file "${GITIGNORE_FILE}" --color=always --line-number --no-heading "$@" |
      fzf --ansi \
          --color 'hl:-1:underline,hl+:-1:underline:reverse' \
          --delimiter ':' \
          --preview "bat --color=always {1} --theme='Solarized (light)' --highlight-line {2}" \
          --preview-window 'up,60%,border-bottom,+{2}+3/3,~3'`
    file="${result%%:*}"
    linenumber=`echo "${result}" | cut -d: -f2`
    if [ ! -z "$file" ]; then
            ${EDITOR:-nvim} +"${linenumber}" "$file"
    fi
}

search $1